spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lowerCaseServiceId: 'true'
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: api-gateway
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
    com:
      kleenxcoder: debug
eureka:
  instance:
    preferIpAddress: 'true'
    metadataMap:
      zone: default
  client:
    preferSameZoneEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
